import os

MUSIXMATCH_API_KEY = os.getenv("MUSIXMATCH_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SPOTIPY_CLIENT_ID = os.getenv("SPOTIPY_CLIENT_ID")
SPOTIPY_CLIENT_SECRET = os.getenv("SPOTIPY_CLIENT_SECRET")
SPOTIPY_REDIRECT_URI = os.getenv("SPOTIPY_REDIRECT_URI")
